# Ising model

The aim of this exercise is to meet the glorious ising model, and torealize that the direct sampling of the probability distribution is useless in this case.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## 1 - Taking confidence with the 2-d standard Ising model

In the 2-d standard Ising model, the nodes are arranged in a two dimensional lattice, let's say of size $L$. Therefore, the total number of spins is $N=L^2$. Each spin is identified by its coordinates $(x,y)$, where $x, y \in \lbrace 1,2, \ldots, L\rbrace$.

The interactions occur only between nearest neighbours of the lattice with a constant coupling coefficient $J$: the spin at $(x,y)$ interact with $(x+1,y)$, $(x-1,y)$, $(x,y+1)$, $(x,y-1)$. We also impose periodic boundary conditions, such that the spin at the boundary $(L, y)$ interact with the spin at the opposite boundary $(0,y)$ (the same is true for the spins at $y=L$ and $y=0$).
As a consequence, the Hamiltonian of the system has this shape:

\begin{equation}
\mathcal{H}\left(\vec{\sigma}\right) = - \sum_{x,y = 1}^{L} \sigma_{x,y} \left[ \frac{J}{2}  \left( \sigma_{x+1,y} + \sigma_{x-1,y} + \sigma_{x,y+1} + \sigma_{x,y-1} \right) + h \right]
\end{equation}

where the spins are binary variables, $\sigma_{x,y} \in \lbrace -1,1 \rbrace$, and the boundary conditions say that $x,y=L+1 = 1$ and $x,y=L=0$.

### 1a - Generate a random state of spins, compute its energy, and magnetization.

First, write a function that generate a random configuration/state, taking as argument the side of the lattice $L$.
This function returns the configuration as a numpy matrix.

In [ ]:
def random_state(side_L):
    return np.random.randint(0, 2, (2,2))*2-1

Second, write the function that compute the energy of a given configuration. This function takes as arguments the configuration, the coupling constant $J$ and the external field $h$.

Be careful about the boundary conditions!

Third, write the function that compute the magnetization taking the configuration as argument.
$$
M(\vec{\sigma}) = \frac{1}{L^2} \sum_{x,y=1}^L \sigma_{x,y}
$$

Now you can try to fix the parameters $L$, $J$ and $h$, generate a random configuration and compute its energy and magnetization.

### 1b - Try to do the same with a configuration having all the spins up.

### 1c - Plot the configuration that you have generated.

For doing a "color map" in which the values stored in a matrix are plotted with different colors depending on their value (excatly our case), you can use plt.imshow as below.

## 2 - Compute the partition function of the system and realize that direct sampling is impossible

The equilibrium distribution of a canonical ensemble is given by the Gibbs measure:

\begin{equation}
\pi\left( \vec{\sigma} \right) = \frac{1}{Z(\beta)} e^{-\beta \; \mathcal{H}\left( \vec{\sigma} \right)  }
\end{equation}

where $\beta$ is proportional to the inverse of the temperature, and the normalization constant is the partition function of the system:

\begin{equation}
Z(\beta) = \sum_{\vec{\sigma}} e^{-\beta \; \mathcal{H}\left( \vec{\sigma} \right)  }
\end{equation}

Note that to compute the partition function, one has to enumerate all the states of the system $\vec{\sigma}$, which, in our case, are all the possible combinations of $+1$ and $-1$ of for all the $N$ spins, therefore $2^N$ states.
The fact that the number of states exponentially increase with $N$ is basically the reason why it is not possible to manage the model simulation by directly sampling the probability distribution $\pi\left( \vec{\sigma} \right)$.


### 2a - Write a function that returns the non-normalized Gibbs weight of a given configuration. 

It takes as arguments the configuration, $\beta$, $J$, and $h$. (Use the energy function that you have written before).

Compute the partition function. To do this you have to enumerate all the possible configurations, and compute the Gibbs measure for each of them. For the enumeration use the use the suggested iterable written below.


In [ ]:
from itertools import product

for i in product([-1,1], repeat=4):
  print('single element', i)
  print('as an array\n', np.array(i).reshape((2,2)))


single element (-1, -1, -1, -1)
as an array
 [[-1 -1]
 [-1 -1]]
single element (-1, -1, -1, 1)
as an array
 [[-1 -1]
 [-1  1]]
single element (-1, -1, 1, -1)
as an array
 [[-1 -1]
 [ 1 -1]]
single element (-1, -1, 1, 1)
as an array
 [[-1 -1]
 [ 1  1]]
single element (-1, 1, -1, -1)
as an array
 [[-1  1]
 [-1 -1]]
single element (-1, 1, -1, 1)
as an array
 [[-1  1]
 [-1  1]]
single element (-1, 1, 1, -1)
as an array
 [[-1  1]
 [ 1 -1]]
single element (-1, 1, 1, 1)
as an array
 [[-1  1]
 [ 1  1]]
single element (1, -1, -1, -1)
as an array
 [[ 1 -1]
 [-1 -1]]
single element (1, -1, -1, 1)
as an array
 [[ 1 -1]
 [-1  1]]
single element (1, -1, 1, -1)
as an array
 [[ 1 -1]
 [ 1 -1]]
single element (1, -1, 1, 1)
as an array
 [[ 1 -1]
 [ 1  1]]
single element (1, 1, -1, -1)
as an array
 [[ 1  1]
 [-1 -1]]
single element (1, 1, -1, 1)
as an array
 [[ 1  1]
 [-1  1]]
single element (1, 1, 1, -1)
as an array
 [[ 1  1]
 [ 1 -1]]
single element (1, 1, 1, 1)
as an array
 [[1 1]
 [1 1]]


You cannot enumerate all the states even for a very small system, e.g. $L > 6$. This makes impossible to compute the average of observables (e.g. the magnetization) using the analytical summation, as well as to extract samples form the probability distribution using direct Montecarlo methods.
